In [16]:
import numpy as np
import pandas as pd
import pathlib
import dotenv
import os

from preference_learning import load_dataframe, UtaWrapper

In [2]:
dotenv.load_dotenv()
X_train, X_test, y_train, y_test = load_dataframe(mode="split")
model = UtaWrapper()
path = pathlib.Path(os.getenv("PROJECT_PATH")) / "models" / "ann_utadis.pt"
model.load_model(path)
y_pred_proba = model.predict_proba(X_test)
y_pred = model.predict(X_test)
# Now, get the indices ordered by the difference
idx = np.argsort(abs(y_pred_proba[:, 1] - 0.5))
idx

array([344, 173, 341, 135, 235,  50, 109, 175, 112, 293,  93, 192, 164,
       234, 221, 316,  79, 100, 182, 170, 136,  52, 268,  96, 239, 252,
       201, 159,  34, 190,  16,  76, 280, 319,   8,  30, 335, 317, 237,
       291, 258, 118,  13, 336, 143, 231,  94, 149,  14, 162,  92,  19,
       168, 241, 312, 340, 230,  85, 250,  10, 137, 103,  54, 331,  87,
       247, 294,  95, 297, 311,  26, 320, 324, 305, 101, 205, 271,   2,
       310,  65,  42, 303,  36,  32, 188,  22,  29, 191, 157, 206, 113,
         5, 147, 272, 302, 315,  45,  84, 179,  68, 129, 274, 257, 180,
       151,   3,  21, 226, 256, 174, 172,   0, 240, 108,  41, 217,  61,
       178, 200, 134, 140, 114, 185,  15, 260, 246, 169,  48, 124, 111,
       295, 131, 342, 288, 199, 273, 249,  23,   7, 141,  99, 218, 313,
       283, 296, 207, 282, 242,  90, 321,  66, 254,  51, 223, 299,  91,
        43, 123, 163,  75,  88, 166, 266, 279, 155, 176, 203, 333,  38,
       309,  25, 261,  11, 327, 228, 181, 334,  40, 204, 106,  6

In [5]:
y_pred_proba[idx]

array([[0.49978715, 0.50021285],
       [0.5005994 , 0.49940062],
       [0.50146663, 0.4985334 ],
       [0.5016153 , 0.4983847 ],
       [0.5016171 , 0.49838293],
       [0.502032  , 0.49796802],
       [0.5023905 , 0.49760953],
       [0.50304794, 0.4969521 ],
       [0.50305444, 0.49694556],
       [0.5037807 , 0.49621925],
       [0.50379133, 0.49620867],
       [0.50380135, 0.49619862],
       [0.50383794, 0.49616206],
       [0.50391984, 0.4960802 ],
       [0.5039216 , 0.49607837],
       [0.5040703 , 0.4959297 ],
       [0.5040721 , 0.49592787],
       [0.5043826 , 0.4956174 ],
       [0.5043874 , 0.4956126 ],
       [0.5044991 , 0.49550095],
       [0.50466335, 0.49533668],
       [0.5047272 , 0.49527282],
       [0.50473374, 0.49526626],
       [0.5048032 , 0.49519685],
       [0.50490284, 0.4950972 ],
       [0.50491536, 0.49508467],
       [0.50499904, 0.49500096],
       [0.5051583 , 0.4948417 ],
       [0.5053888 , 0.4946112 ],
       [0.505405  , 0.494595  ],
       [0.

In [4]:
y_pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [4]:
X_test.iloc[idx[:3]]

buying     maint  doors  persons  lug_boot  safety
344     1.0  1.000000    1.0      1.0       0.0     1.0
173     1.0  0.666667    1.0      1.0       0.5     1.0
341     1.0  1.000000    1.0      1.0       0.0     0.5

In [12]:
y_test.iloc[idx[:3]]

class
344      0
173      0
341      0

In [10]:
y_pred_proba[idx[:3]]

array([[0.49978715, 0.50021285],
       [0.5005994 , 0.49940062],
       [0.50146663, 0.4985334 ]], dtype=float32)

In [11]:
y_pred[idx[:3]]

array([[1],
       [0],
       [0]])

In [22]:
print(model.predict(pd.Series([1.0,1,2/3,1,0.0,1]))) # doors 1 -> 2 then 1 -> 0
print(model.predict(pd.Series([1.0,1,1.0,1.0,0.5,1.0]))) # maintenance 2/3 -> 1 then 0 -> 1
print(model.predict(pd.Series([1.0,1,1.0,1.0,0.0,1]))) # safety 0.5 -> 1 then 0 -> 1

[[0]]
[[1]]
[[1]]
